# -*- coding: utf-8 -*-
# Generated by Django 1.9c1 on 2016-02-18 21:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import moments.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Moment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to=moments.models.get_upload_file_name)),
                ('caption', models.TextField(blank=True, null=True)),
                ('moment_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('moment_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('loc_name', models.CharField(blank=True, max_length=240, null=True)),
                ('loc_id', models.CharField(blank=True, max_length=240, null=True)),
                ('loc_vicinity', models.CharField(blank=True, max_length=240, null=True)),
                ('moment_created', models.DateTimeField(auto_now_add=True)),
                ('moment_removed', models.BooleanField(default=False)),
                ('tagged_nonce', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('user_moment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moment_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-moment_created'],
            },
        ),
        migrations.CreateModel(
            name='MomentComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
                ('comment_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_user', to=settings.AUTH_USER_MODEL)),
                ('moment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moment_comment', to='moments.Moment')),
            ],
        ),
        migrations.CreateModel(
            name='MomentLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moment_liked', models.BooleanField(default=False)),
                ('liked_date', models.DateTimeField(auto_now=True)),
                ('liked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_user', to=settings.AUTH_USER_MODEL)),
                ('moment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moment_like', to='moments.Moment')),
            ],
        ),
    ]
